/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./components/Badge.vue')['default']
    CustomToast: typeof import('./components/CustomToast.vue')['default']
    DemoSite: typeof import('./components/DemoSite.vue')['default']
    DemoSites: typeof import('./components/DemoSites.vue')['default']
    DisplayIcon: typeof import('./components/DisplayIcon.vue')['default']
  }
}
