// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badge: typeof import('./components/Badge.vue')['default']
    CustomToast: typeof import('./components/CustomToast.vue')['default']
    DemoSite: typeof import('./components/DemoSite.vue')['default']
    DemoSites: typeof import('./components/DemoSites.vue')['default']
    DisplayIcon: typeof import('./components/DisplayIcon.vue')['default']
  }
}

export {}
