// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CustomToast: typeof import('./.vitepress/theme/components/CustomToast.vue')['default']
    DemoSite: typeof import('./.vitepress/theme/components/DemoSite.vue')['default']
    DemoSites: typeof import('./.vitepress/theme/components/DemoSites.vue')['default']
    DisplayIcon: typeof import('./.vitepress/theme/components/DisplayIcon.vue')['default']
  }
}

export { }
